# Generated by Django 5.0.7 on 2024-08-01 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contact_created_at_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 6, 55, 10, 703189, tzinfo=datetime.timezone.utc)),
        ),
    ]
